version: 1

reviews:
  enable: true
  auto_review:
    ignore_usernames: []
    labels: ["!wip", "!draft"]
    title_keywords: ["!wip", "!draft"]
    base_branches:
      include:
        - "*"
  on:
    pull_request: true
    push: false
  comments:
    inline: true
    summary: true
  branches:
    include:
      - "*"

rules:
  complexity: error
  duplication: error
  style: error
  security: error
  refactor: error  # Adding refactor suggestions as errors

fail:
  on: [error, suggestion]   # Fail on both errors and suggestions
