version: 1

reviews:
  enable: true
  auto_review:
    ignore_usernames: []
    labels: ["!wip", "!draft"]
    title_keywords: ["!wip", "!draft"]
  on:
    pull_request: true
    push: false
  comments:
    inline: true
    summary: true
  branches:
    include:
      - "*"

rules:
  complexity: warn
  duplication: warn
  style: suggest
  security: error
