version: 1

reviews:
  enable: true
  auto_review:
    ignore_usernames: []
    labels: ["!wip", "!draft"]
    title_keywords: ["!wip", "!draft"]
    base_branches:
      include:
        - "*"  # Allow reviews on all base branches
  on:
    pull_request: true
    push: false
  comments:
    inline: true
    summary: true
  branches:
    include:
      - "*"

rules:
  complexity: error
  duplication: error
  style: error
  security: error

# 👇 This makes CodeRabbit mark the check as failed if any issues are found
fail_on_issues: true
