export const canadaProvinces = [
    { value: 'AB', label: 'Alberta' },
    { value: 'BC', label: 'British Columbia' },
    { value: 'MB', label: 'Manitoba' },
    { value: 'NB', label: 'New Brunswick' },
    { value: 'NL', label: 'Newfoundland and Labrador' },
    { value: 'NS', label: 'Nova Scotia' },
    { value: 'ON', label: 'Ontario' },
    { value: 'PE', label: 'Prince Edward Island' },
    { value: 'QC', label: 'Quebec' },
    { value: 'SK', label: 'Saskatchewan' },
    { value: 'NT', label: 'Northwest Territories' },
    { value: 'NU', label: 'Nunavut' },
    { value: 'YT', label: 'Yukon' }
];

export const usStates = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' }
];

export const mexicoStates = [
    { value: 'AG', label: 'Aguascalientes' },
    { value: 'BC', label: 'Baja California' },
    { value: 'BS', label: 'Baja California Sur' },
    { value: 'CM', label: 'Campeche' },
    { value: 'CS', label: 'Chiapas' },
    { value: 'CH', label: 'Chihuahua' },
    { value: 'CO', label: 'Coahuila' },
    { value: 'CL', label: 'Colima' },
    { value: 'DF', label: 'Ciudad de México' },
    { value: 'DG', label: 'Durango' },
    { value: 'GT', label: 'Guanajuato' },
    { value: 'GR', label: 'Guerrero' },
    { value: 'HG', label: 'Hidalgo' },
    { value: 'JA', label: 'Jalisco' },
    { value: 'MX', label: 'Estado de México' },
    { value: 'MI', label: 'Michoacán' },
    { value: 'MO', label: 'Morelos' },
    { value: 'NA', label: 'Nayarit' },
    { value: 'NL', label: 'Nuevo León' },
    { value: 'OA', label: 'Oaxaca' },
    { value: 'PU', label: 'Puebla' },
    { value: 'QT', label: 'Querétaro' },
    { value: 'QR', label: 'Quintana Roo' },
    { value: 'SL', label: 'San Luis Potosí' },
    { value: 'SI', label: 'Sinaloa' },
    { value: 'SO', label: 'Sonora' },
    { value: 'TB', label: 'Tabasco' },
    { value: 'TM', label: 'Tamaulipas' },
    { value: 'TL', label: 'Tlaxcala' },
    { value: 'VE', label: 'Veracruz' },
    { value: 'YU', label: 'Yucatán' },
    { value: 'ZA', label: 'Zacatecas' }
];




export const thailandProvinces = [
    { value: 'BK', label: 'Bangkok' },
    { value: 'CN', label: 'Chiang Mai' },
    { value: 'PN', label: 'Phuket' },
    { value: 'CB', label: 'Chonburi' },
    { value: 'NR', label: 'Nakhon Ratchasima' },
    { value: 'NS', label: 'Nakhon Si Thammarat' },
    { value: 'CNX', label: 'Chiang Rai' },
    { value: 'CR', label: 'Chanthaburi' },
    { value: 'CT', label: 'Chai Nat' },
    { value: 'CK', label: 'Chaiyaphum' },
    { value: 'CP', label: 'Kalasin' },
    { value: 'KR', label: 'Krabi' },
    { value: 'LG', label: 'Lampang' },
    { value: 'LN', label: 'Lamphun' },
    { value: 'LB', label: 'Loei' },
    { value: 'LC', label: 'Lopburi' },
    { value: 'MP', label: 'Mae Hong Son' },
    { value: 'MS', label: 'Maha Sarakham' },
    { value: 'MG', label: 'Mukdahan' },
    { value: 'NT', label: 'Nakhon Nayok' },
    { value: 'NB', label: 'Nakhon Pathom' },
    { value: 'NSR', label: 'Nakhon Sawan' },
    { value: 'NA', label: 'Nan' },
    { value: 'NSI', label: 'Narathiwat' },
    { value: 'NPT', label: 'Nonthaburi' },
    { value: 'NTN', label: 'Nong Bua Lamphu' },
    { value: 'NN', label: 'Nong Khai' },
    { value: 'PA', label: 'Pattani' },
    { value: 'PR', label: 'Phang Nga' },
    { value: 'PS', label: 'Phatthalung' },
    { value: 'PE', label: 'Phayao' },
    { value: 'PH', label: 'Phetchabun' },
    { value: 'PC', label: 'Phetchaburi' },
    { value: 'PL', label: 'Phichit' },
    { value: 'PK', label: 'Phitsanulok' },
    { value: 'PG', label: 'Phrae' },
    { value: 'PT', label: 'Phra Nakhon Si Ayutthaya' },
    { value: 'PP', label: 'Phrae' },
    { value: 'PTB', label: 'Prachuap Khiri Khan' },
    { value: 'PPK', label: 'Prachinburi' },
    { value: 'PRN', label: 'Ranong' },
    { value: 'RR', label: 'Ratchaburi' },
    { value: 'RI', label: 'Rayong' },
    { value: 'RT', label: 'Roi Et' },
    { value: 'SK', label: 'Sa Kaeo' },
    { value: 'SP', label: 'Sakon Nakhon' },
    { value: 'SRB', label: 'Samut Prakan' },
    { value: 'SRN', label: 'Samut Sakhon' },
    { value: 'SRS', label: 'Samut Songkhram' },
    { value: 'SAR', label: 'Saraburi' },
    { value: 'SB', label: 'Satun' },
    { value: 'SSC', label: 'Si Sa Ket' },
    { value: 'SKH', label: 'Sing Buri' },
    { value: 'SN', label: 'Songkhla' },
    { value: 'SPT', label: 'Sukhothai' },
    { value: 'ST', label: 'Suphan Buri' },
    { value: 'SUR', label: 'Surat Thani' },
    { value: 'SY', label: 'Surin' },
    { value: 'TR', label: 'Tak' },
    { value: 'TG', label: 'Trang' },
    { value: 'TY', label: 'Trat' },
    { value: 'UD', label: 'Ubon Ratchathani' },
    { value: 'UK', label: 'Udon Thani' },
    { value: 'UN', label: 'Uthai Thani' },
    { value: 'UP', label: 'Uttaradit' },
    { value: 'YC', label: 'Yala' },
    { value: 'YSA', label: 'Yasothon' }
];


export const bahrainGovernorates = [
    { value: 'CC', label: 'Capital' },
    { value: 'NR', label: 'Northern' },
    { value: 'MU', label: 'Muharraq' },
    { value: 'SO', label: 'Southern' }
];

export const countries =[
    { value: "US", label: "United States" },
    { value: "Canada", label: "Canada" },
    { value: "Mexico", label: "Mexico" },
    { value: "Thailand", label: "Thailand" },
    { value: "Bahrain", label: "Bahrain" },
  ]